local i18n = {}

-- =========================
-- ENGLISH (EN)
-- =========================
i18n.en = {
	messages = {
		["pd-flag"] = "This image of a <b>[[w:Vexillology|vexillology]]</b> or <b>[[w:Flag|flag]]</b> is <b>ineligible for copyright</b> and therefore in the <b>[[w:Public domain|public domain]]</b>, because it consists entirely of information that is common property and contains no original authorship.",
		["pd-shapes"] = "This image of [[w:Geometry|simple geometry]] is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		["pd-textlogo"] = "This logo image consists only of simple geometric shapes or text. It <b>does not meet the [[wikimediacommons:Commons:Threshold_of_originality|threshold of originality]]</b> needed for copyright protection, and is therefore in the <b>[[w:Public domain|public domain]]</b>. Although it is free of copyright restrictions, this image may still be subject to [[wikimediacommons:Commons:Non-copyright restrictions|other restrictions]].",
		["pd-author-with"] = "This work has been released into the [[w:Public domain|public domain]] by its author, $1. This applies worldwide.<br/><small>In some countries this may not be legally possible; if so:</small><br/><i>$1 grants anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.</i>",
		["pd-author-self"] = "I, the copyright holder of this work, release this work into the [[w:Public domain|public domain]]. This applies worldwide.<br/><small>In some countries this may not be legally possible; if so:</small><br/><i>I grant anyone the right to use this work for any purpose, without any conditions, unless such conditions are required by law.</i>",
		["pd-ineligible"] = "This work is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]] because it consists entirely of information that is [[wikimediacommons:Commons:Threshold of originality|common property and contains no original authorship]].",
		["pd-chart"] = "This chart is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		["pd-map"] = "This map is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		["pd-chem"] = "This image of a simple [[w:Structural formula|<b>structural formula</b>]] is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		["pd-text"] = 'The depicted text is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]] because it is not a “literary work” or other protected type in sense of the local copyright law. Facts, data, and unoriginal information which is common property without sufficiently creative authorship in a general typeface or basic handwriting, and simple geometric shapes are not protected by copyright. <small>This tag does not generally apply to all images of texts. Particular countries can have different legal definition of the “literary work” as the subject of copyright and different courts interpretation practices. Some countries protect almost every written work, while other countries protect distinctively artistic or scientific texts and databases only. Extent of creativeness, function and length of the text can be relevant. The copyright protection can be limited to the literary form – the included information itself can be excluded from protection.</small>',
		["pd-sign"] = "This simple sign is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		["pd-wpdc"] = "This (election) apportionment diagram is <b>ineligible for [[w:Copyright|copyright]]</b> and therefore in the [[w:Public domain|<b>public domain</b>]], because it consists entirely of information that is common property and contains no original authorship.",
		
		["cc-by-sa-4.0"] = '<div style="font-size:1.4em; text-align: center; font-weight: bold;">[https://creativecommons.org/licenses/by-sa/4.0/deed.en Attribution-ShareAlike 4.0 International] (CC BY-SA 4.0)</div><ul><div style="font-size:1.2em; font-weight: bold;">You are free:</div><li><b>Share</b> — copy and redistribute the material in any medium or format for any purpose, even commercially.</li><li><b>Adapt</b> — remix, transform, and build upon the material for any purpose, even commercially.</li><li>The licensor cannot revoke these freedoms as long as you follow the license terms.</li><div style="font-size:1.2em; font-weight: bold;">Under the following terms:</div><li><b>Attribution</b> — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.</li><li><b>Share Alike</b> — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.</li><li><b>No additional restrictions</b> — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.</li></ul>',
		["cc-by-sa-3.0-vn"] = '<div style="font-size:1.4em; text-align: center; font-weight: bold;">[https://creativecommons.org/licenses/by-sa/3.0/vn/deed.en Attribution-ShareAlike 3.0 Vietnam] (CC BY-SA 3.0 VN)</div><ul><div style="font-size:1.2em; font-weight: bold;">You are free:</div><li><b>Share</b> — copy and redistribute the material in any medium or format for any purpose, even commercially.</li><li><b>Adapt</b> — remix, transform, and build upon the material for any purpose, even commercially.</li><li>The licensor cannot revoke these freedoms as long as you follow the license terms.</li><div style="font-size:1.2em; font-weight: bold;">Under the following terms:</div><li><b>Attribution</b> — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.</li><li><b>Share Alike</b> — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.</li><li><b>No additional restrictions</b> — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.</li></ul>',
		
		["mit"] = '<center>This file is licensed under the Expat License, sometimes known as the <b>MIT License:</b></center><hr/><i>Copyright © $1 $2</i><br/><br/>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:<br/><br/>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.<br/><br/>The Software is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the Software or the use or other dealings in the Software.<hr/><center>To uploader: MIT License has various versions, you may want to specify the license more precisely. Click {{T|CGeo}} to see details.</center>',
		["apache"] = '<p>Copyright © $1 $2 </p><p>Licensed under the [[w:Apache License|Apache License]], Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.</p>',
		
		["fictitious-flag"] = "This flag is fictitious, proposed, or unofficial, although it may look similar to an official flag. Such flags should usually not be used in articles, unless they are in widespread unofficial use.",
		["nazi"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image shows (or resembles) a symbol that was used by the National Socialist (NSDAP/Nazi) government of Germany or an organization closely associated to it, or another party which <b>has been banned by the [[w:Federal Constitutional Court|Federal Constitutional Court of Germany]]</b>.<p>The use of insignia of organizations that <b>have been banned in [[w:Germany|Germany]]</b> (like the Nazi [[w:Swastika|swastika]] or the [[w:Arrow Cross|arrow cross]]) may also be <b>illegal in [[w:Austria|Austria]], [[w:Brazil|Brazil]], the [[w:Czech Republic|Czech Republic]], [https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006070719&idArticle=LEGIARTI000006419560&dateTexte=20081221 France], [[w:Hungary|Hungary]], [[w:Poland|Poland]], [[w:Russia|Russia]], [[w:Ukraine|Ukraine]] and other countries</b>, depending on context. In Germany, the applicable law is [https://www.gesetze-im-internet.de/stgb/__86a.html paragraph 86a] of the criminal code (StGB), in Poland – Art. 256 of the [https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19970880553 criminal code] (Dz.U. 1997 nr 88 poz. 553).</p>',
		["naziflag"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image contains or resembles a <b>flag</b> or <b>[[w:Reichskriegsflagge|Reichskriegsflagge]]</b> associated with the government of the National Socialist (NSDAP/Nazi), or with organizations closely related to it. Depending on the context and applicable laws, the public display or use of symbols of organizations <b>banned in [[W:Germany|Germany]]</b> may also be <b>illegal in several other countries...</b><p>Additionally, some similar flags or symbols may be <b>restricted or prohibited by the [[TRSAB Organization]] and certain communities</b> due to their sensitive historical and social associations.</p>',
		["non-nazi"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image of a swastika resembles the swastika that was used by the National Socialist (NSDAP/Nazi) government of Germany... This ban, however, does not apply to swastikas that are of a religious nature, including ones used by Buddhism, Hinduism and Jainism.',
		["falungong"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image of a swastika resembles the swastika that was used by the [[w:Falun Gong|Falun Gong]] or an organization closely associated to it...<p>The use of insignia similar to organizations that have been banned in Mainland China <b>may also be illegal in [[w:Russia|Russia]] and other countries,</b> depending on context.</p>',
		["communist"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/><b>This image contains a symbol [[w:Bans on communist symbols|prohibited]] by law in some nations</b>, owing to it being a representation of communism, socialism, or a similar governmental structure; or of an associated political party/organization. Imagery covered may include the [[w:Hammer and sickle|hammer and sickle]], [[w:Red star|red star]], emblems/insignias, [[w:Red flag (politics)|flags]] or images of leaders.',
		["z"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image shows (or resembles) a symbol used by the [[w:Russia|Russian Federation]] and its [[w:Russian Armed Forces|Armed Forces]], an organization closely associated to it, or another party <b>advocating or glorifying wars of aggression or aggressive conduct</b>.<p>The use of these insignias <b>may be prohibited by law in the [[w:Czech Republic|Czech Republic]], [[w:Germany|Germany]], [[w:Kazakhstan|Kazakhstan]], [[w:Kyrgyzstan|Kyrgyzstan]], [[w:Latvia|Latvia]], [[w:Lithuania|Lithuania]], [[w:Moldova|Moldova]], [[w:Poland|Poland]], [[w:Ukraine|Ukraine]] and other countries</b>, depending on context.</p>',
		["teikoku"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image shows (or resembles) a symbol that was used by the Empire of Japan and its Armed Forces or an organization closely associated to it, or another party of <b>advocating or glorifying wars of aggression or aggressive conduct</b> under the <b>[[w:Law on the Protection of Heroes and Martyrs|Law of the People\'s Republic of China]]</b> on the Protection of Heroes and Martyrs.<p>The use of insignias <b>may also be illegal in [[w:South Korea|South Korea]], [[w:Russia|Russia]] and other countries</b>, depending on context.</p>',
		["southvietnam"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/><b>This image is or contains a symbol or symbols [[w:vi:Tuyên truyền chống Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam|prohibited]] by [[W:Vietnam|Vietnam]]\'s [[w:National Assembly of Vietnam|National Assembly]]</b>, due to representations of [[W:South Vietnam|South Vietnam]], or similar governmental structures; or of organizations associated with said. Applicable law is [https://www.policinglaw.info/assets/downloads/2015_Criminal_Code_of_Vietnam_(English_translation).pdf Article 117] of the 2015 Criminal code.<p>Imagery covered may include the [[W:Flag of South Vietnam|Flag of South Vietnam]] and emblems/insignias.</p>',
		["vietnamgroup"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image, or the category has a portion or the whole image with symbol(s) used by [[w:Dao Minh Quan#Political affiliations|Provisional National Government of Vietnam]], [[w:Việt Tân|Viet Tan]], [[w:United Front for the Liberation of Oppressed Races|United Front for the Liberation of Oppressed Races]], [[w:Degar Central Highlands|Degar Central Highlands]] , or their associated groups. Use of these symbols are <b>forbidden</b> per [https://www.policinglaw.info/assets/downloads/2015_Criminal_Code_of_Vietnam_(English_translation).pdf Article 117 of 2015 criminal code].<p><b>Please note that all organizations noted in this template are declared or designated as terrorist organizations. These symbols are allowed for non-reactionary journalistic purposes only. You are solely responsible for ensuring that you do not violate counter-terrorist laws, or supporting them.</b></p>',
		["israel"] = "The display or use of the Israeli flag or related insignia may be restricted or prohibited under local laws in the following countries: Afghanistan, Algeria, Bangladesh, Iran, Iraq, Kuwait, Lebanon, Libya, Pakistan, Qatar, Saudi Arabia, Syria, Yemen. Before redistributing or publicly displaying this image, please verify applicable regulations in your jurisdiction.",
		["lgbtq"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image or video file contains a symbol that represents sexual and gender minorities, including lesbian, gay, bisexual and transgender.<p>Use of these symbols <b>may be subject to punishment according to applicable laws</b> in <b>[[w:Afghanistan|Afghanistan]], [[w:Iran|Iran]], [[w:Russia|Russia]], [[w:Saudi Arabia|Saudi Arabia]], [[w:Uganda|Uganda]], the [[w:United Arab Emirates|United Arab Emirates]], etc.</b></p>',
		["antilgbtq"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image contains a symbol that represents a negative or bigoted attitude towards sexual and gender minorities, including lesbian, gay, bisexual and transgender.<p>Using these symbols for the purpose of discriminating against sexual and gender minorities <b>may be subject to punishment under anti-discrimination laws</b>.</p>',
		["apartheid"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/>This image depicts or resembles the [[w:Flag of South Africa (1928–1994)|flag of South Africa from 1928 to 1994]], which is <b>prohibited as hate speech and may be criminally prosecutable when displayed publicly in South Africa</b>, except for genuine artistic, academic, or journalistic purposes in the public interest.',
		["ai"] = '<span style="font-size:21px;font-weight:bold;">Legal Disclaimer</span><br/><b>Most [[w:AI art|image-generating AI]] models were trained using works that are protected by [[w:Copyright|copyright]]</b>. In some cases, such models can output content with major <b>copyrightable image elements</b> which are identical to or derivative of the original training data... <b>there is a risk that AI-generated media uploaded on Commons may violate the rights of the authors of the original works</b>.',
		
		["error-no-license"] = "CGen Error: No valid license code type found.",
		["error-missing-parameters"] = "CGen Error: Missing required parameters.",
		["error-extra-missing"] = "CGen Error: Extra body content is required for this type.",
		
		["default-authorlic"] = "The author(s)"
	},
	categories = {
		["pd-flag"] = "[[Category:Images Vexillology]]",
		["pd-shapes"] = "[[Category:Images Shapes]]",
		["pd-textlogo"] = "[[Category:Images TextLogo]]",
		["pd-author"] = "[[Category:Images PD-Author]]",
		["pd-ineligible"] = "[[Category:Images PD-Ineligible]]",
		["pd-chart"] = "[[Category:Images PD-Chart]]",
		["pd-chem"] = "[[Category:Images PD-Chem]]",
		["pd-text"] = "[[Category:Images PD-Text]]",
		["cc-by-sa-4.0"] = "[[Category:Images CC BY-SA 4.0]]",
		["mit"] = "[[Category:MIT Licensed Files]]",
		["apache"] = "[[Category:Apache License]]",
		["fictional-flag"] = "[[Category:Images Fictional Flag]]",
		["nazi"] = "[[Category:Nazi related licence]]",
		["naziflag"] = "[[Category:Nazi Flag related licence]]",
		["swastika"] = "[[Category:Swastika related licence]]",
		["falungong"] = "[[Category:Falun Gong related licence]]",
		["communist"] = "[[Category:Communist related licence]]",
		["russia-militarism"] = "[[Category:Russian Militarism related articles]]",
		["japan-empire"] = "[[Category:Japan Empire related articles]]",
		["south-vietnam"] = "[[Category:South Vietnam related articles]]",
		["vietnam-parties"] = "[[Category:Vietnamese Political Parties related articles]]",
		["israel"] = "[[Category:Israel related articles]]",
		["lgbtq"] = "[[Category:LGBTQ related articles]]",
		["anti-lgbtq"] = "[[Category:Anti LGBTQ related articles]]",
		["apartheid"] = "[[Category:Apartheid related articles]]",
		["ai"] = "[[Category:AI related articles]]"
	},
	headers = {
		self = "<center><b>$1, the copyright holder of this work, hereby publishes it under the following license(s):</b></center>",
		screenshot = "<center>This <b>screenshot</b> either does not contain <b>copyright-eligible</b> parts or visuals of [[w:Copyright|<b>copyrighted</b>]] software, or the author has released it under a [[w:Free license|<b>free license</b>]], and as such follows the licensing guidelines. <b>Free software license:</b></center>",
		art = "<center>This is a faithful photographic reproduction of a two-dimensional, public domain work of art. The work of art itself is in the public domain for the following reason:</center>"
	},
	footers = {
		self = "<center>You may select the license of your choice.</center>",
		screenshot = "<center><b>Note:</b> if the screenshot shows any work that is not a direct result of the program code itself, the <b>license</b> for that work <b>must</b> be indicated separately.</center>"
	},
}

-- =========================
-- VIETNAMESE (VI)
-- =========================
i18n.vi = {
	messages = {
		["pd-flag"] = "Hình ảnh này của một <b>[[w:vi:Kỳ học|lá cờ]]</b> <b>không đủ điều kiện để bảo hộ bản quyền</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn chứa đựng thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-shapes"] = "Hình ảnh <b>[[w:vi:Hình học|hình học đơn giản]]</b> này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-textlogo"] = "Hình ảnh logo này chỉ bao gồm các hình học hoặc văn bản đơn giản. Nó <b>không đạt được [[wikimediacommons:Commons:Threshold_of_originality|ngưỡng sáng tạo]]</b> cần thiết để được bảo vệ bản quyền, và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>. Mặc dù không bị hạn chế bởi bản quyền, hình ảnh này vẫn có thể chịu sự điều chỉnh của [[wikimediacommons:Commons:Non-copyright restrictions|các hạn chế phi bản quyền khác]].",
		["pd-author-with"] = "Tác phẩm này đã được tác giả của nó, $1, phát hành vào [[w:vi:Phạm vi công cộng|phạm vi công cộng]]. Điều này áp dụng trên toàn thế giới.<br/><small>Tại một số quốc gia, điều này có thể không hợp lệ về mặt pháp lý; nếu vậy:</small><br/><i>$1 cấp cho bất kỳ ai quyền sử dụng tác phẩm này cho bất kỳ mục đích nào, không kèm theo bất kỳ điều kiện nào, trừ khi luật pháp yêu cầu những điều kiện đó.</i>",
		["pd-author-self"] = "Tôi, người giữ bản quyền của tác phẩm này, qua đây phát hành tác phẩm này vào [[w:vi:Phạm vi công cộng|phạm vi công cộng]]. Điều này áp dụng trên toàn thế giới.<br/><small>Tại một số quốc gia, điều này có thể không hợp lệ về mặt pháp lý; nếu vậy:</small><br/><i>Tôi cấp cho bất kỳ ai quyền sử dụng tác phẩm này cho bất kỳ mục đích nào, không kèm theo bất kỳ điều kiện nào, trừ khi luật pháp yêu cầu những điều kiện đó.</i>",
		["pd-ineligible"] = "Tác phẩm này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b> bởi vì nó hoàn toàn bao gồm các thông tin là [[wikimediacommons:Commons:Threshold of originality|tài sản chung và không có tác quyền gốc]].",
		["pd-chart"] = "Biểu đồ này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-map"] = "Bản đồ này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-chem"] = "Hình ảnh của một [[w:vi:Công thức cấu tạo|<b>công thức cấu tạo</b>]] hóa học đơn giản này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-text"] = 'Đoạn văn bản được miêu tả <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b> vì nó không phải là "tác phẩm văn học" hoặc loại hình được bảo vệ theo luật bản quyền địa phương. Sự kiện, dữ liệu, thông tin thiếu tính nguyên bản, phông chữ chung hay hình học cơ bản không được bảo vệ bản quyền. <small>Thẻ này không áp dụng cho mọi hình ảnh chứa văn bản, tùy thuộc vào định nghĩa pháp lý của từng quốc gia về "tác phẩm văn học".</small>',
		["pd-sign"] = "Biển báo đơn giản này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		["pd-wpdc"] = "Sơ đồ phân bổ (bầu cử) này <b>không đủ điều kiện bảo hộ [[w:vi:Bản quyền|bản quyền]]</b> và do đó thuộc <b>[[w:vi:Phạm vi công cộng|phạm vi công cộng]]</b>, bởi vì nó hoàn toàn bao gồm các thông tin là tài sản chung và không có tác quyền gốc.",
		
		["cc-by-sa-4.0"] = '<div style="font-size:1.4em; text-align: center; font-weight: bold;">[https://creativecommons.org/licenses/by-sa/4.0/deed.vi Ghi công–Chia sẻ tương tự 4.0 Quốc tế] (CC BY-SA 4.0)</div><ul><div style="font-size:1.2em; font-weight: bold;">Bạn được tự do:</div><li><b>Chia sẻ</b> — sao chép và phân phối lại tài liệu dưới bất kỳ phương tiện hoặc định dạng nào cho bất kỳ mục đích nào, kể cả thương mại.</li><li><b>Sửa đổi</b> — phối trộn, biến đổi và xây dựng dựa trên tài liệu cho bất kỳ mục đích nào, kể cả thương mại.</li><li>Người cấp phép không thể thu hồi những quyền tự do này miễn là bạn tuân theo các điều khoản của giấy phép.</li><div style="font-size:1.2em; font-weight: bold;">Theo các điều khoản sau:</div><li><b>Ghi công</b> — Bạn phải ghi công phù hợp, cung cấp liên kết đến giấy phép và cho biết nếu có thay đổi. Bạn có thể làm như vậy bằng bất kỳ cách thức hợp lý nào, nhưng không được gợi ý rằng người cấp phép chứng thực bạn hoặc việc sử dụng của bạn.</li><li><b>Chia sẻ tương tự</b> — Nếu bạn phối trộn, biến đổi hoặc xây dựng dựa trên tài liệu, bạn phải phân phối các đóng góp của mình theo cùng một giấy phép với bản gốc.</li><li><b>Không có hạn chế bổ sung</b> — Bạn không được áp dụng các điều khoản pháp lý hoặc biện pháp công nghệ nhằm hạn chế người khác thực hiện bất cứ điều gì mà giấy phép cho phép.</li></ul>',
		["cc-by-sa-3.0-vn"] = '<div style="font-size:1.4em; text-align: center; font-weight: bold;">[https://creativecommons.org/licenses/by-sa/3.0/vn/deed.vi Ghi công–Chia sẻ tương tự 3.0 Việt Nam] (CC BY-SA 3.0 VN)</div><ul><div style="font-size:1.2em; font-weight: bold;">Bạn được tự do:</div><li><b>Chia sẻ</b> — sao chép và phân phối lại tài liệu dưới bất kỳ phương tiện hoặc định dạng nào cho bất kỳ mục đích nào, kể cả thương mại.</li><li><b>Sửa đổi</b> — phối trộn, biến đổi và xây dựng dựa trên tài liệu cho bất kỳ mục đích nào, kể cả thương mại.</li><div style="font-size:1.2em; font-weight: bold;">Theo các điều khoản sau:</div><li><b>Ghi công</b> — Bạn phải ghi công phù hợp, cung cấp liên kết đến giấy phép và cho biết nếu có thay đổi.</li><li><b>Chia sẻ tương tự</b> — Nếu bạn phối trộn, biến đổi hoặc xây dựng dựa trên tài liệu, bạn phải phân phối các đóng góp của mình theo cùng một giấy phép với bản gốc.</li></ul>',
		
		["mit"] = '<center>Tập tin này được cấp phép theo Giấy phép Expat, hay còn được biết đến với tên gọi <b>MIT License:</b></center><hr/><i>Bản quyền © $1 $2</i><br/><br/>Qua đây, quyền lợi được cấp miễn phí cho bất kỳ người nào có được bản sao của phần mềm này và các tệp tài liệu liên quan ("Phần mềm"), được phép xử lý Phần mềm mà không có giới hạn, bao gồm nhưng không giới hạn ở quyền sử dụng, sao chép, sửa đổi, hợp nhất, xuất bản, phân phối, cấp phép lại và/hoặc bán bản sao của Phần mềm, và cho phép những người được cung cấp Phần mềm làm như vậy, với các điều kiện sau:<br/><br/>Thông báo bản quyền ở trên và thông báo cấp phép này phải được bao gồm trong tất cả các bản sao hoặc phần quan trọng của Phần mềm.<br/><br/>PHẦN MỀM ĐƯỢC CUNG CẤP "NHƯ NGUYÊN TRẠNG", KHÔNG CÓ BẤT KỲ ĐẢM BẢO NÀO, RÕ RÀNG HAY NGỤ Ý, BAO GỒM NHƯNG KHÔNG GIỚI HẠN Ở CÁC ĐẢM BẢO VỀ KHẢ NĂNG THƯƠNG MẠI, TÍNH PHÙ HỢP CHO MỘT MỤC ĐÍCH CỤ THỂ VÀ KHÔNG VI PHẠM.<hr/><center>Gửi người tải lên: MIT License có nhiều phiên bản khác nhau, bạn có thể muốn chỉ định giấy phép chính xác hơn. Nhấn {{T|CGeo}} để xem chi tiết.</center>',
		["apache"] = '<p>Bản quyền © $1 $2 </p><p>Được cấp phép theo [[w:vi:Apache License|Apache License]], Phiên bản 2.0 ("Giấy phép"); bạn không được sử dụng tệp này ngoại trừ tuân thủ Giấy phép. Bạn có thể nhận được bản sao của Giấy phép tại https://www.apache.org/licenses/LICENSE-2.0. Trừ khi luật pháp hiện hành yêu cầu hoặc có thỏa thuận bằng văn bản, phần mềm được phân phối theo Giấy phép này được phân phối trên cơ sở "NHƯ NGUYÊN TRẠNG", KHÔNG CÓ ĐẢM BẢO HOẶC ĐIỀU KIỆN DƯỚI BẤT KỲ HÌNH THỨC NÀO, dù rõ ràng hay ngụ ý. Xem Giấy phép để biết các quyền và giới hạn được chi phối cụ thể theo ngôn ngữ trong Giấy phép.</p>',
		
		["fictitious-flag"] = "Lá cờ này là hư cấu, được đề xuất hoặc không chính thức, mặc dù nó có thể trông giống với một lá cờ chính thức. Những lá cờ như vậy thường không nên được sử dụng trong các bài viết, trừ khi chúng được sử dụng không chính thức một cách rộng rãi.",
		["nazi"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này hiển thị (hoặc giống với) một biểu tượng từng được sử dụng bởi chính phủ Quốc xã (NSDAP/Nazi) của Đức hoặc một tổ chức có liên hệ chặt chẽ với nó, hoặc một đảng phái khác <b>đã bị [[w:vi:Tòa án Hiến pháp Liên bang Đức|Tòa án Hiến pháp Liên bang Đức]] cấm</b>.<p>Việc sử dụng phù hiệu của các tổ chức <b>đã bị cấm ở [[w:vi:Đức|Đức]]</b> (như chữ Vạn của Đức Quốc xã hoặc cờ chữ thập mũi tên) cũng có thể <b>bất hợp pháp ở Áo, Brazil, Cộng hòa Séc, Pháp, Hungary, Ba Lan, Nga, Ukraine và các quốc gia khác</b>, tùy thuộc vào bối cảnh.</p>',
		["naziflag"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này chứa hoặc giống với <b>cờ</b> hoặc <b>[[w:vi:Reichskriegsflagge|Cờ Chiến tranh của Đế chế]]</b> liên quan đến chính quyền Quốc xã (NSDAP/Nazi), hoặc các tổ chức liên quan chặt chẽ. Tùy thuộc vào bối cảnh và luật pháp hiện hành, việc hiển thị công khai các biểu tượng của các tổ chức <b>bị cấm ở [[w:vi:Đức|Đức]]</b> cũng có thể là <b>bất hợp pháp tại một số quốc gia khác...</b>',
		["non-nazi"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh chữ vạn này giống với chữ vạn đã được chính phủ Quốc xã sử dụng... Tuy nhiên, lệnh cấm này không áp dụng cho chữ vạn có tính chất tôn giáo, bao gồm cả những chữ vạn được sử dụng trong Phật giáo, Ấn Độ giáo và Kỳ Na giáo.',
		["falungong"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này giống với biểu tượng được sử dụng bởi [[w:vi:Pháp Luân Công|Pháp Luân Công]] hoặc một tổ chức liên quan...<p>Việc sử dụng các phù hiệu tương tự như các tổ chức đã bị cấm ở Trung Quốc Đại lục <b>cũng có thể bị coi là bất hợp pháp ở [[w:vi:Nga|Nga]] và các quốc gia khác,</b> tùy thuộc vào bối cảnh.</p>',
		["communist"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/><b>Hình ảnh này chứa một biểu tượng [[w:vi:Cấm các biểu tượng cộng sản|bị cấm]] theo luật ở một số quốc gia</b>, vì nó đại diện cho chủ nghĩa cộng sản, chủ nghĩa xã hội, hoặc một tổ chức chính trị liên quan. Hình ảnh được đề cập có thể bao gồm [[w:vi:Búa liềm|búa liềm]], [[w:vi:Sao đỏ|sao đỏ]], biểu tượng/phù hiệu, [[w:vi:Cờ đỏ (chính trị)|cờ]] hoặc hình ảnh của các nhà lãnh đạo.',
		["z"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này hiển thị (hoặc giống với) một biểu tượng được sử dụng bởi [[w:vi:Nga|Liên bang Nga]] và [[w:vi:Lực lượng Vũ trang Liên bang Nga|Lực lượng Vũ trang]] của quốc gia này, một tổ chức có liên hệ chặt chẽ hoặc một bên khác <b>ủng hộ hoặc tôn vinh các cuộc chiến tranh xâm lược hoặc hành vi xâm lược</b>.<p>Việc sử dụng các phù hiệu này <b>có thể bị pháp luật cấm tại Cộng hòa Séc, Đức, Kazakhstan, Kyrgyzstan, Latvia, Litva, Moldova, Ba Lan, Ukraine và các quốc gia khác</b>, tùy thuộc vào bối cảnh.</p>',
		["teikoku"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này hiển thị (hoặc giống với) một biểu tượng từng được Đế quốc Nhật Bản và Lực lượng Vũ trang của nó sử dụng... <b>ủng hộ hoặc tôn vinh các cuộc chiến tranh xâm lược</b>.<p>Việc sử dụng các phù hiệu <b>cũng có thể bất hợp pháp ở [[w:vi:Hàn Quốc|Hàn Quốc]], [[w:vi:Nga|Nga]] và các quốc gia khác</b>, tùy thuộc vào bối cảnh.</p>',
		["southvietnam"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/><b>Hình ảnh này là hoặc chứa (các) biểu tượng [[w:vi:Tuyên truyền chống Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam|bị cấm]] bởi [[W:vi:Quốc hội (Việt Nam)|Quốc hội Việt Nam]]</b>, do là biểu tượng đại diện cho [[W:vi:Việt Nam Cộng hòa|Việt Nam Cộng hòa]], hoặc các cơ cấu chính quyền/tổ chức liên quan. Luật áp dụng là Điều 117 của Bộ luật Hình sự 2015.<p>Hình ảnh được đề cập có thể bao gồm [[W:vi:Quốc kỳ Việt Nam Cộng hòa|Quốc kỳ Việt Nam Cộng hòa]] và các biểu tượng/phù hiệu.</p>',
		["vietnamgroup"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này có chứa (các) biểu tượng được sử dụng bởi [[w:vi:Chính phủ Quốc gia Việt Nam Lâm thời|Chính phủ Quốc gia Việt Nam Lâm thời]], [[w:vi:Việt Tân|Việt Tân]], [[w:vi:FULRO|FULRO]], hoặc các nhóm liên quan. Việc sử dụng các biểu tượng này bị <b>nghiêm cấm</b> theo Điều 117 của Bộ luật hình sự 2015.<p><b>Xin lưu ý rằng tất cả các tổ chức được ghi nhận trong bản mẫu này đều được tuyên bố là tổ chức khủng bố tại Việt Nam. Các biểu tượng này chỉ được cho phép cho mục đích báo chí không mang tính phản động. Bạn hoàn toàn chịu trách nhiệm đảm bảo rằng bạn không vi phạm luật chống khủng bố.</b></p>',
		["israel"] = "Việc hiển thị hoặc sử dụng quốc kỳ Israel hoặc các phù hiệu liên quan có thể bị hạn chế hoặc cấm theo luật địa phương tại các quốc gia sau: Afghanistan, Algeria, Bangladesh, Iran, Iraq, Kuwait, Lebanon, Libya, Pakistan, Qatar, Ả Rập Xê Út, Syria, Yemen. Trước khi phân phối lại hoặc hiển thị công khai hình ảnh này, vui lòng xác minh các quy định hiện hành trong khu vực pháp lý của bạn.",
		["lgbtq"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh hoặc tệp video này chứa một biểu tượng đại diện cho các nhóm thiểu số về tính dục và giới tính (LGBTQ).<p>Việc sử dụng các biểu tượng này <b>có thể bị trừng phạt theo luật pháp hiện hành</b> tại <b>Afghanistan, Iran, Nga, Ả Rập Xê Út, Uganda, Các Tiểu vương quốc Ả Rập Thống nhất, v.v.</b></p>',
		["antilgbtq"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này chứa một biểu tượng đại diện cho thái độ tiêu cực hoặc cố chấp đối với các nhóm thiểu số tính dục và giới tính.<p>Việc sử dụng các biểu tượng này nhằm mục đích phân biệt đối xử <b>có thể bị trừng phạt theo luật chống phân biệt đối xử</b> tại nhiều quốc gia.</p>',
		["apartheid"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/>Hình ảnh này mô tả hoặc giống với cờ của Nam Phi từ năm 1928 đến năm 1994, <b>bị cấm do coi là ngôn từ kích động thù địch và có thể bị truy tố hình sự khi hiển thị công khai tại Nam Phi</b>, ngoại trừ các mục đích nghệ thuật, học thuật hoặc báo chí đích thực phục vụ lợi ích công cộng.',
		["ai"] = '<span style="font-size:21px;font-weight:bold;">Tuyên bố từ chối trách nhiệm pháp lý</span><br/><b>Hầu hết các mô hình [[w:vi:Nghệ thuật AI|AI tạo hình ảnh]] đều được đào tạo bằng cách sử dụng các tác phẩm được bảo hộ [[w:vi:Bản quyền|bản quyền]]</b>. Do đó, <b>có rủi ro là các phương tiện do AI tạo ra được tải lên Commons có thể vi phạm quyền của tác giả các tác phẩm gốc</b>.',
		
		["error-no-license"] = "Lỗi CGen: Không tìm thấy loại mã giấy phép hợp lệ.",
		["error-missing-parameters"] = "Lỗi CGen: Thiếu các tham số bắt buộc.",
		["error-extra-missing"] = "Lỗi CGen: Nội dung phần body (extra) là bắt buộc đối với loại này.",
		
		["default-author"] = "Các tác giả"
	},
	categories = {
		["pd-flag"] = "[[Thể loại:Hình ảnh Vexillology]]",
		["pd-shapes"] = "[[Thể loại:Hình ảnh Shapes]]",
		["pd-textlogo"] = "[[Thể loại:Hình ảnh TextLogo]]",
		["pd-author"] = "[[Thể loại:Hình ảnh PD-Author]]",
		["pd-ineligible"] = "[[Thể loại:Hình ảnh PD-Ineligible]]",
		["pd-chart"] = "[[Thể loại:Hình ảnh PD-Chart]]",
		["pd-chem"] = "[[Thể loại:Hình ảnh PD-Chem]]",
		["pd-text"] = "[[Thể loại:Hình ảnh PD-Text]]",
		["cc-by-sa-4.0"] = "[[Thể loại:Hình ảnh CC BY-SA 4.0]]",
		["mit"] = "[[Thể loại:Tập tin giấy phép MIT]]",
		["apache"] = "[[Thể loại:Giấy phép Apache]]",
		["fictional-flag"] = "[[Thể loại:Hình ảnh cờ hư cấu]]",
		["nazi"] = "[[Thể loại:Giấy phép liên quan đến Đức Quốc Xã]]",
		["naziflag"] = "[[Thể loại:Giấy phép liên quan đến cờ Đức Quốc Xã]]",
		["swastika"] = "[[Thể loại:Giấy phép liên quan đến chữ Vạn]]",
		["falungong"] = "[[Thể loại:Giấy phép liên quan đến Pháp Luân Công]]",
		["communist"] = "[[Thể loại:Giấy phép liên quan đến Cộng sản]]",
		["russia-militarism"] = "[[Thể loại:Bài viết liên quan đến chủ nghĩa quân phiệt Nga]]",
		["japan-empire"] = "[[Thể loại:Bài viết liên quan đến Đế quốc Nhật Bản]]",
		["south-vietnam"] = "[[Thể loại:Bài viết liên quan đến Việt Nam Cộng hòa]]",
		["vietnam-parties"] = "[[Thể loại:Bài viết liên quan đến các Đảng phái Chính trị Việt Nam]]",
		["israel"] = "[[Thể loại:Bài viết liên quan đến Israel]]",
		["lgbtq"] = "[[Thể loại:Bài viết liên quan đến LGBTQ]]",
		["anti-lgbtq"] = "[[Thể loại:Bài viết liên quan đến chống LGBTQ]]",
		["apartheid"] = "[[Thể loại:Bài viết liên quan đến Apartheid]]",
		["ai"] = "[[Thể loại:Bài viết liên quan đến AI]]"
	},
	headers = {
		self = "<center><b>$1 (người giữ bản quyền của tác phẩm này), qua đây phát hành nó theo (các) giấy phép sau:</b></center>",
		screenshot = "<center><b>Ảnh chụp màn hình</b> này không chứa các phần <b>đủ điều kiện bản quyền</b> hoặc hình ảnh của phần mềm <b>có bản quyền</b>, hoặc tác giả đã phát hành nó theo một <b>giấy phép tự do</b>. <b>Giấy phép phần mềm tự do:</b></center>",
		art = "<center>Đây là một bản sao chụp chân thực của một tác phẩm nghệ thuật hai chiều thuộc phạm vi công cộng. Bản thân tác phẩm nghệ thuật này thuộc phạm vi công cộng vì lý do sau:</center>"
	},
	footers = {
		self = "<center>Bạn có thể chọn giấy phép mà mình muốn.</center>",
		screenshot = "<center><b>Lưu ý:</b> nếu ảnh chụp màn hình hiển thị bất kỳ tác phẩm nào không phải là kết quả trực tiếp của chính mã chương trình, thì <b>giấy phép</b> cho tác phẩm đó <b>phải</b> được chỉ định riêng biệt.</center>"
	}
}

return i18n
